server:
  port: 8090
  contextPath : /test
spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/chytest?characterEncoding=utf8&useSSL=true
      username: root
      password: root
      drive-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      filters: log4j
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20